### ISSUE TITLE
Wrong Screenshot in EnablingTheSystemEventAuditLog.rst	for Audit Other Account Management Events

### ISSUE THREAD

**Issue by apiperCIS** [planglois925/Test_Controls_Doc#2]

**Comment by apiperCIS** [comment]
In Appendix/EnablingTheSystemEventAuditLog.rst

Under *Account Management*, select *Audit Other Account Management Events*. Ensure that *Configure the following audit events* is checked, and that *Success* is checked. 

.. figure:: _static/AuditComputerAccountManagement.png
   :align: center
   
   Audit Other Account Management Events  

AuditComputerAccountManagement.png should point to a different .png

**Comment by planglois925** [comment]
[https://github.com/planglois925/Test_Controls_Doc/blob/master/Appendix/EnablingTheSystemEventAuditLog.rst](https://github.com/planglois925/Test_Controls_Doc/blob/master/Appendix/EnablingTheSystemEventAuditLog.rst)

**Comment by thejoshpit** [comment]
Thank you @apiperCIS for identifying this issue. The screenshot was updated.

#4e6ee014bf2f5c31184f4f04b5ae1e0dddfaa287

**Comment by thejoshpit** [comment]
Issue closed.
